### ISSUE TITLE
Older Boost version

### ISSUE THREAD

**Issue by AGaliuzov** [vinniefalco/Beast#205]
Hello @vinniefalco, we are using Boost 1.56 and in documentations here I see restrictions to 1.58 or higher.

Are there any known issues with 1.56? In case It will work fine may I send the pull request?

**Comment by vinniefalco** [comment]
I usually run all the automated tests with a more recent Boost version. I am building Beast to become a Boost library (formal review early next year). When that happens, Beast won't be available with earlier versions of Boost. You can try building Beast with an older Boost, but it might not work. I can't remember what the problem was. I wouldn't mind looking over your proposed changes to get Beast compiling in Boost. If they are very minor I would consider it but there's no guarantee.

**Comment by vinniefalco** [comment]
I'll close this for now, feel free to re-open it if there is new information.
