### ISSUE TITLE
newbie question on thread safety and strands

### ISSUE THREAD

**Issue by vchang-akamai** [vinniefalco/Beast#360]
The thread safety page states "The asynchronous interface supports one active read and one active write simultaneously. "
[http://vinniefalco.github.io/beast/beast/websocket/threads.html](url)

I've been wrapping all my async_* calls for a websocket with a single explicit strand associated with that websocket.  Does the above statement mean that I should be using two strands per websocket: one for reads and one for writes?

**Comment by vinniefalco** [comment]
No. The strand just means protects the stream so that two completion handlers do not execute concurrently. You still need to make sure that you don't do two reads or writes at once, without an intermediate completion handler. For example, this code produces undefined behavior:
```
template<class NextLayer>
void undefined(beast::websocket::stream<NextLayer>& ws);
{
  beast::multi_buffer b1;
  beast::websocket::opcode op1;
  ws.async_read(op1, b1,
    []()
    {
    });
  beast::multi_buffer b2;
  beast::websocket::opcode op2;
  ws.async_read(op1, b2,
    []()
    {
    });
```

There cannot be more than one active read and one active write at the same time.

**Comment by vchang-akamai** [comment]
Thanks for the clarification! I have some things to fix... :-)
