### ISSUE TITLE
CMake tests/examples option

### ISSUE THREAD

**Issue by xsacha** [vinniefalco/Beast#442]
By default all tests/examples are compiled. Could these be made in to options?
See: https://github.com/xsacha/Beast/blob/hunter-b50/CMakeLists.txt
> option(Beast_BUILD_EXAMPLES "Build examples" OFF)
> option(Beast_BUILD_TESTS "Build tests" OFF)

Can submit this part as a pull if you want but you probably want them enabled by default?

**Comment by vinniefalco** [comment]
Hmm...why wouldn't we want to build those?

**Comment by xsacha** [comment]
If we want to include Beast in a submodule or another project, we will not be concerned with tests or examples but just want the linkage and includes.

**Comment by vinniefalco** [comment]
If you're using Beast in another project, you don't need Beast's CMakeLists.txt at all, just add an `include_directories` line to your own CMake and that's all you need!

**Comment by xsacha** [comment]
This is only because there is another issue in the CMakeLists: no target.
If you have a Beast target, it provides linkage and includes automatically. This is how CMake is designed.
If you can provide a Beast interface, all my projects can link to the same interface no matter where Beast is located and what it links to.

**Comment by vinniefalco** [comment]
Your commit is intriguing. I am interested in simplifying the link targets for the tests and examples. However, when using Beast in another project you do not need program_options, coroutine, context, filesystem, or thread - Beast doesn't depend on those (just the tests).

I am also puzzled why you have removed `GroupSources` - that's a very important function because it helps to organize the generated Visual Studio project files which I use exclusively for development.

**Comment by xsacha** [comment]
Misunderstanding on my part. I would change it to only Boost::system in this case.

I wasn't suggesting going so far yet. Baby steps :) Not all the changes in that commit are suggested for here. Some of them are changes due to unrelated package-management.

**Comment by vinniefalco** [comment]
This is now in **develop**
