### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by harrishancock** [vinniefalco/Beast#521]
Little nits on current master branch:

- `boost::asio_handler_type` is misspelled [here](https://github.com/vinniefalco/Beast/blob/master/include/beast/core/async_result.hpp#L35).

- [`handler_type`](http://vinniefalco.github.io/beast/beast/ref/beast__handler_type.html) and [`async_return_type`](http://vinniefalco.github.io/beast/beast/ref/beast__async_return_type.html) both duplicate [`async_result`](http://vinniefalco.github.io/beast/beast/ref/beast__async_result.html)'s content.

**Comment by vinniefalco** [comment]
1. It says `boost::asio::handler_type`, isn't that correct? http://www.boost.org/doc/libs/1_64_0/boost/asio/handler_type.hpp

2. Nothing I can really do about that, its an artifact of doxygen's handling of template aliases.

**Comment by harrishancock** [comment]
1. Click the link I posted in the first bullet.

2. Gotcha, c'est la vie.

**Comment by harrishancock** [comment]
I'm sorry, the misspelling is `boost::asio_async_result`.

**Comment by vinniefalco** [comment]
willfix

**Comment by vinniefalco** [comment]
@harrishancock This is a big ask, and if you are otherwise preoccupied I will of course understand; *but*, the formal review is 9 days out. If you want to go through every public interface (or even some of them) and anything which you think is questionable or weak I will try to address it if I agree. I've been doing this in the last two days, but of course I am biased and not really objective. On the other hand, it does look pretty good (what did you think of the `prepare_payload` change, and the change to `Fields` requirements?)

**Comment by harrishancock** [comment]
I'll do what I can! My schedule is severely squeezed right now, though.

To be honest, I have only used the websocket and core parts of Beast so far, still no HTTP (though that might change this week), so I don't have educated opinions on the changes you mentioned yet.

I will have feedback for you on the composed op tutorial very shortly, btw. Will send by email tonight.
