### ISSUE TITLE
http_server example based on boost::asio::spawn

### ISSUE THREAD

**Issue by e-fominov** [vinniefalco/Beast#89]
boost::asio offers asynchronous implementation based on Coroutines [that can use single thread for multiple parallel requests](http://www.boost.org/doc/libs/1_61_0/doc/html/boost_asio/example/cpp03/spawn/echo_server.cpp)

It would be nice to have such example code for http server

**Comment by vinniefalco** [comment]
Note that the provided asynchronous server example can also use a single thread for multiple requests, just set the number of threads to 1 in the constructor.

**Comment by e-fominov** [comment]
Yes, but "spawn" technology uses Boost.Coroutines internally and can produce code that will be as simple as http_sync_server but it will be asynchronous
I will try to make sample and show you. I think it will be interesting, as Beast has its own asyncronour read/write methods and we should check if they can be safely used with Coroutines

**Comment by vinniefalco** [comment]
I'm sure that Beast works with coroutines, because some of the unit tests use them:
https://github.com/vinniefalco/Beast/blob/master/test/websocket/stream.cpp#L436

I have to be honest, part of my objection to providing a coroutine server example is that I don't want to have to maintain two copies of each server, especially because I plan on making significant changes to those servers (which I would have to replicate for the coroutine versions).

**Comment by e-fominov** [comment]
I accept your position. Beast should have 100% reliable and compatible low-level http/websocket protocol. And making servers should be done later or somewhere else. If I will find any problems with coroutines, I will make test for it

BTW, any plans for HTTP2?

**Comment by vinniefalco** [comment]
Yes, I have a design for what HTTP/2 would look like. First, note that the `message` class is already HTTP/2 compatible. One complication is that HTTP/2 requires a stateful connection, in order to decompress the headers and keep track of request/response channels. So there has to be an object wrapping a next layer that represents an active HTTP/2 session. Very much like how the current `websocket::stream` is designed.

**Comment by vinniefalco** [comment]
Closing this since its addressed by the tests which use coroutines
